/**
 * PDF Download Utility
 * Converts contract HTML content to a professional PDF document
 * using jsPDF + html-to-image inside an isolated, hidden iframe
 * to guarantee zero CSS pollution on the main web application.
 */
import { toCanvas } from 'html-to-image';
import { jsPDF } from 'jspdf';

const PDF_MARGIN = 15; // mm
const PAGE_WIDTH = 210; // A4 width in mm
const PAGE_HEIGHT = 297; // A4 height in mm
const CONTENT_WIDTH = PAGE_WIDTH - PDF_MARGIN * 2;

/**
 * Convert HTML content to a properly formatted PDF and trigger download.
 * Uses an isolated hidden iframe so contract template CSS styles never leak into the main UI.
 * @param contentHtml - The contract HTML content snapshot
 * @param fileName - Output filename (without extension)
 * @param docTitle - Optional title to display at the top of the PDF
 */
export async function downloadContractAsPdf(
  contentHtml: string | null | undefined,
  fileName: string,
  docTitle?: string,
): Promise<void> {
  if (!contentHtml) {
    // Fallback: create a simple PDF with a message
    const pdf = new jsPDF('p', 'mm', 'a4');
    pdf.setFontSize(16);
    pdf.text('No document content available', PDF_MARGIN, 50);
    pdf.save(`${fileName}.pdf`);
    return;
  }

  // Create an isolated hidden iframe
  const iframe = document.createElement('iframe');
  iframe.style.cssText = `
    position: fixed;
    left: -9999px;
    top: 0;
    width: 794px;
    height: 1123px;
    border: none;
    opacity: 0;
    pointer-events: none;
    z-index: -9999;
  `;
  document.body.appendChild(iframe);

  try {
    const doc = iframe.contentDocument || iframe.contentWindow?.document;
    if (!doc) throw new Error('Could not access iframe document');

    // Build the isolated HTML document inside iframe
    doc.open();
    doc.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8" />
          <style>
            body {
              margin: 0;
              padding: 40px 48px;
              background: #ffffff !important;
              color: #1a1a2e !important;
              font-family: '72', '72full', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
              font-size: 13px;
              line-height: 1.6;
              width: 794px;
              box-sizing: border-box;
            }
            h1, h2, h3, h4 { color: #0a2342; margin-top: 20px; margin-bottom: 8px; font-weight: 700; }
            h1 { font-size: 20px; border-bottom: 2px solid #0a6ed1; padding-bottom: 6px; }
            h2 { font-size: 16px; }
            h3 { font-size: 14px; }
            p { margin: 0 0 8px 0; }
            table { width: 100%; border-collapse: collapse; margin: 12px 0; }
            th, td { border: 1px solid #d0d5dd; padding: 8px 12px; text-align: left; font-size: 12px; }
            th { background: #f0f4ff; font-weight: 700; color: #0a2342; }
            tr:nth-child(even) td { background: #fafbfc; }
            strong, b { color: #0a2342; }
            hr { border: none; border-top: 1px solid #e2e8f0; margin: 16px 0; }
            ul, ol { padding-left: 20px; margin: 8px 0; }
            li { margin-bottom: 4px; }
            img { max-width: 100%; height: auto; }
          </style>
        </head>
        <body>
          ${docTitle ? `<div style="text-align:center;margin-bottom:24px;padding-bottom:12px;border-bottom:2px solid #0a6ed1;"><h1 style="margin:0;font-size:18px;border:none;">${docTitle}</h1></div>` : ''}
          ${contentHtml}
          <div style="margin-top:32px;padding-top:12px;border-top:1px solid #e2e8f0;text-align:center;font-size:10px;color:#94a3b8;">
            Generated by Heliflow • ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}
          </div>
        </body>
      </html>
    `);
    doc.close();

    // Wait for fonts and images inside iframe to settle
    await new Promise(resolve => setTimeout(resolve, 300));

    const iframeBody = doc.body;

    // Capture the iframe body to high-resolution canvas
    const canvas = await toCanvas(iframeBody, {
      quality: 1,
      pixelRatio: 2,
      backgroundColor: '#ffffff',
    });

    const pdf = new jsPDF('p', 'mm', 'a4');
    const imgData = canvas.toDataURL('image/png');
    const imgWidth = CONTENT_WIDTH;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    const usablePageHeight = PAGE_HEIGHT - PDF_MARGIN * 2;

    let remainingHeight = imgHeight;
    let currentPage = 0;

    while (remainingHeight > 0) {
      if (currentPage > 0) {
        pdf.addPage();
      }

      const yOffset = PDF_MARGIN - currentPage * usablePageHeight;

      pdf.addImage(
        imgData,
        'PNG',
        PDF_MARGIN,
        yOffset,
        imgWidth,
        imgHeight,
        undefined,
        'FAST',
      );

      remainingHeight -= usablePageHeight;
      currentPage++;
    }

    pdf.save(`${fileName}.pdf`);
  } catch (err) {
    console.error('PDF download error:', err);
    throw err;
  } finally {
    if (document.body.contains(iframe)) {
      document.body.removeChild(iframe);
    }
  }
}
