/**
 * PDF Download Utility
 * Converts contract HTML content to a professional PDF document
 * using jspdf + html-to-image
 */
import { toCanvas } from 'html-to-image';
import { jsPDF } from 'jspdf';

const PDF_MARGIN = 15; // mm
const PAGE_WIDTH = 210; // A4 width in mm
const PAGE_HEIGHT = 297; // A4 height in mm
const CONTENT_WIDTH = PAGE_WIDTH - PDF_MARGIN * 2;

/**
 * Convert HTML content to a properly formatted PDF and trigger download.
 * @param contentHtml - The contract HTML content snapshot
 * @param fileName - Output filename (without extension)
 * @param docTitle - Optional title to display at the top of the PDF
 */
export async function downloadContractAsPdf(
  contentHtml: string | null | undefined,
  fileName: string,
  docTitle?: string,
): Promise<void> {
  if (!contentHtml) {
    // Fallback: create a simple PDF with a message
    const pdf = new jsPDF('p', 'mm', 'a4');
    pdf.setFontSize(16);
    pdf.text('No document content available', PDF_MARGIN, 50);
    pdf.save(`${fileName}.pdf`);
    return;
  }

  // Create a temporary off-screen container to render the HTML
  const container = document.createElement('div');
  container.innerHTML = contentHtml;
  container.style.cssText = `
    position: fixed;
    left: -9999px;
    top: 0;
    width: 794px;
    padding: 48px 56px;
    background: #ffffff;
    font-family: 'Georgia', 'Times New Roman', serif;
    font-size: 14px;
    line-height: 1.7;
    color: #1a1a2e;
  `;

  // Add base styling for common HTML elements
  const style = document.createElement('style');
  style.textContent = `
    body { margin: 0; padding: 0; font-family: 'Georgia', 'Times New Roman', serif; color: #1a1a2e; }
    h1, h2, h3, h4 { color: #0a2342; margin-top: 24px; margin-bottom: 10px; font-weight: 700; }
    h1 { font-size: 22px; border-bottom: 2px solid #0a6ed1; padding-bottom: 8px; }
    h2 { font-size: 18px; }
    h3 { font-size: 15px; }
    p { margin: 0 0 10px 0; }
    table { width: 100%; border-collapse: collapse; margin: 14px 0; }
    th, td { border: 1px solid #d0d5dd; padding: 8px 12px; text-align: left; font-size: 12px; }
    th { background: #f0f4ff; font-weight: 700; color: #0a2342; }
    tr:nth-child(even) td { background: #fafbfc; }
    strong, b { color: #0a2342; }
    hr { border: none; border-top: 1px solid #e2e8f0; margin: 20px 0; }
    ul, ol { padding-left: 24px; margin: 8px 0; }
    li { margin-bottom: 4px; }
    img { max-width: 100%; height: auto; }
  `;
  container.prepend(style);

  // Add header if title provided
  if (docTitle) {
    const headerEl = document.createElement('div');
    headerEl.style.cssText = `
      text-align: center;
      margin-bottom: 32px;
      padding-bottom: 16px;
      border-bottom: 3px solid #0a6ed1;
    `;
    const titleEl = document.createElement('h1');
    titleEl.textContent = docTitle;
    titleEl.style.cssText = 'margin: 0; font-size: 20px; border: none; color: #0a2342;';
    headerEl.appendChild(titleEl);

    // Add a subtle subtitle line
    const subEl = document.createElement('div');
    subEl.style.cssText = 'font-size: 11px; color: #64748b; margin-top: 4px; text-transform: uppercase; letter-spacing: 1px;';
    subEl.textContent = 'Heliflow Contract Document';
    headerEl.appendChild(subEl);

    container.prepend(headerEl);
  }

  // Add footer watermark
  const footerEl = document.createElement('div');
  footerEl.style.cssText = `
    margin-top: 32px;
    padding-top: 12px;
    border-top: 1px solid #e2e8f0;
    text-align: center;
    font-size: 10px;
    color: #94a3b8;
  `;
  footerEl.textContent = `Generated by Heliflow • ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}`;
  container.appendChild(footerEl);

  document.body.appendChild(container);

  try {
    // Wait for fonts and images to load
    await document.fonts?.ready;
    await new Promise(resolve => setTimeout(resolve, 200));

    // Convert the container to a high-resolution canvas
    const canvas = await toCanvas(container, {
      quality: 1,
      pixelRatio: 2,
      cacheBust: true,
      backgroundColor: '#ffffff',
    });

    const pdf = new jsPDF('p', 'mm', 'a4');
    const imgData = canvas.toDataURL('image/png');
    const imgWidth = CONTENT_WIDTH;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    const usablePageHeight = PAGE_HEIGHT - PDF_MARGIN * 2; // 267mm

    let remainingHeight = imgHeight;
    let currentPage = 0;

    while (remainingHeight > 0) {
      if (currentPage > 0) {
        pdf.addPage();
      }

      // Shift the image upward by the accumulated page height
      // so each subsequent page shows the next vertical section
      const yOffset = PDF_MARGIN - currentPage * usablePageHeight;

      pdf.addImage(
        imgData,
        'PNG',
        PDF_MARGIN,
        yOffset,
        imgWidth,
        imgHeight,
        undefined,
        'FAST',
      );

      remainingHeight -= usablePageHeight;
      currentPage++;
    }

    pdf.save(`${fileName}.pdf`);
  } finally {
    document.body.removeChild(container);
  }
}
