import type { PaletteCategory } from '../../types/formBuilder';

export const FIELD_PALETTE: PaletteCategory[] = [
  {
    category: 'Text & Input Fields',
    items: [
      {
        type: 'text',
        label: 'Text Input',
        icon: 'Type',
        description: 'Single-line text input field',
        defaultConfig: {
          label: 'Single Line Text',
          placeholder: 'Enter text...',
          required: false,
          readOnly: false,
          width: 'full',
        },
      },
      {
        type: 'textarea',
        label: 'Text Area',
        icon: 'AlignLeft',
        description: 'Multi-line text area field',
        defaultConfig: {
          label: 'Multi-line Text',
          placeholder: 'Enter detailed description...',
          required: false,
          readOnly: false,
          width: 'full',
        },
      },
      {
        type: 'number',
        label: 'Number',
        icon: 'Hash',
        description: 'Numeric value input with min/max',
        defaultConfig: {
          label: 'Number',
          placeholder: '',
          required: false,
          readOnly: false,
          width: 'half',
        },
      },
      {
        type: 'email',
        label: 'Email',
        icon: 'Mail',
        description: 'Email address with validation',
        defaultConfig: {
          label: 'Email Address',
          placeholder: '',
          required: false,
          readOnly: false,
          width: 'half',
        },
      },
      {
        type: 'phone',
        label: 'Phone',
        icon: 'Phone',
        description: 'Phone number input',
        defaultConfig: {
          label: 'Phone Number',
          placeholder: '',
          required: false,
          readOnly: false,
          width: 'half',
        },
      },
      {
        type: 'currency',
        label: 'Currency',
        icon: 'DollarSign',
        description: 'Amount with currency symbol & dropdown selector',
        defaultConfig: {
          label: 'Amount',
          placeholder: '',
          currency: 'KES',
          required: false,
          readOnly: false,
          width: 'half',
        },
      },
    ],
  },
  {
    category: 'Date & Time',
    items: [
      {
        type: 'date',
        label: 'Date Picker',
        icon: 'Calendar',
        description: 'Select a date',
        defaultConfig: {
          label: 'Select Date',
          required: false,
          readOnly: false,
          width: 'half',
        },
      },
      {
        type: 'time',
        label: 'Time Picker',
        icon: 'Clock',
        description: 'Select time of day',
        defaultConfig: {
          label: 'Select Time',
          required: false,
          readOnly: false,
          width: 'half',
        },
      },
    ],
  },
  {
    category: 'Selection & Choice',
    items: [
      {
        type: 'dropdown',
        label: 'Dropdown',
        icon: 'ChevronDown',
        description: 'Single select dropdown list',
        defaultConfig: {
          label: 'Dropdown Select',
          placeholder: 'Select an option',
          required: false,
          readOnly: false,
          width: 'half',
          options: ['Option 1', 'Option 2', 'Option 3'],
        },
      },
      {
        type: 'multiselect',
        label: 'Multi Select',
        icon: 'ListFilter',
        description: 'Multiple selection dropdown',
        defaultConfig: {
          label: 'Multi Select',
          placeholder: 'Select options',
          required: false,
          readOnly: false,
          width: 'half',
          options: ['Option A', 'Option B', 'Option C'],
        },
      },
      {
        type: 'checkbox',
        label: 'Checkbox',
        icon: 'CheckSquare',
        description: 'Checkbox item group',
        defaultConfig: {
          label: 'Checkboxes',
          required: false,
          readOnly: false,
          width: 'full',
          options: ['Item 1', 'Item 2'],
        },
      },
      {
        type: 'radio',
        label: 'Radio Button',
        icon: 'CircleDot',
        description: 'Single choice radio group',
        defaultConfig: {
          label: 'Radio Options',
          required: false,
          readOnly: false,
          width: 'full',
          options: ['Choice 1', 'Choice 2'],
        },
      },
    ],
  },
  {
    category: 'Media & Uploads',
    items: [
      {
        type: 'file',
        label: 'File Upload',
        icon: 'UploadCloud',
        description: 'Upload documents or images',
        defaultConfig: {
          label: 'Attachment / File',
          helpText: 'Supported formats: PDF, PNG, JPG, DOCX (Max 10MB)',
          required: false,
          readOnly: false,
          width: 'full',
        },
      },
      {
        type: 'signature',
        label: 'Signature',
        icon: 'PenTool',
        description: 'Digital signature capture pad',
        defaultConfig: {
          label: 'Digital Signature',
          helpText: 'Draw or type your signature below',
          required: false,
          readOnly: false,
          width: 'full',
        },
      },
    ],
  },
  {
    category: 'Structure & Content',
    items: [
      {
        type: 'heading',
        label: 'Heading',
        icon: 'Heading',
        description: 'Section heading text block',
        defaultConfig: {
          label: 'Section Header',
          content: 'New Section',
          width: 'full',
          required: false,
          readOnly: false,
        },
      },
      {
        type: 'paragraph',
        label: 'Paragraph',
        icon: 'FileText',
        description: 'Descriptive text paragraph',
        defaultConfig: {
          label: 'Instructional Text',
          content: 'Please fill out all required details accurately before submitting.',
          width: 'full',
          required: false,
          readOnly: false,
        },
      },
      {
        type: 'divider',
        label: 'Divider',
        icon: 'Minus',
        description: 'Horizontal separator line',
        defaultConfig: {
          label: 'Divider',
          width: 'full',
          required: false,
          readOnly: false,
        },
      },
    ],
  },
  {
    category: 'Enterprise Pickers',
    items: [
      {
        type: 'user_picker',
        label: 'User Picker',
        icon: 'UserCheck',
        description: 'Select an internal user or manager',
        defaultConfig: {
          label: 'Assignee / Internal User',
          placeholder: 'Search user...',
          required: false,
          readOnly: false,
          width: 'half',
        },
      },
      {
        type: 'vendor_picker',
        label: 'Vendor Picker',
        icon: 'Building',
        description: 'Select from vendor directory',
        defaultConfig: {
          label: 'Target Vendor',
          placeholder: 'Select vendor...',
          required: false,
          readOnly: false,
          width: 'half',
        },
      },
    ],
  },
];
